-- Active: 1669499925647@@127.0.0.1@3306@juicedb

CREATE TABLE tbClient(
    CPF VARCHAR(11),
    NAME VARCHAR(100),
    STREET VARCHAR(150),
    DISTRICT VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    CEP VARCHAR(8),
    BIRTHDAY DATE,
    AGE SMALLINT,
    GENDER ENUM('Masc','Femi'),
    CREDITLIMIT DOUBLE,
    MINBUY FLOAT,
    NEWCLIENT BIT(1)
);



DROP TABLE if EXISTS tbClient