[tool.poetry]
name = "code"
version = "0.1.0"
description = ""
authors = ["Matias Herklotz <matias.herklotz@globalhitss.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
