version: "3.4"
services:
  auto-ml-deploy:
    tty: true
    image: "auto-ml-deploy"
    stdin_open: true
    build:
      context: .
      target: "development"
    volumes:
      - ".:/app"
    environment:
      - ENV_FOR_DYNACONF=development
      - DATABASE_URL=localhost
      - DATABASE_NAME=auto-ml-db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
    ports:
      - "8000:8000"
    networks:
      - db_nw

  auto-ml-db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auto-ml-db
    networks:
      - db_nw

networks:
  db_nw:
    driver: bridge

volumes:
  auto-ml-db: